# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tapi.proto\x12\x03\x61pi\"@\n\x04User\x12\x1d\n\x07profile\x18\x01 \x01(\x0b\x32\x0c.api.Profile\x12\x19\n\x05\x63\x61\x63he\x18\x02 \x01(\x0b\x32\n.api.Point\"$\n\x07Profile\x12\x0b\n\x03\x61ge\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x16\n\x05Point\x12\r\n\x05value\x18\x01 \x01(\x05\x32[\n\tUserGuide\x12&\n\x08GetPoint\x12\x0c.api.Profile\x1a\n.api.Point\"\x00\x12&\n\tListUsers\x12\n.api.Point\x1a\t.api.User\"\x00\x30\x01\x62\x06proto3')
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='api.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile', full_name='api.User.profile', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cache', full_name='api.User.cache', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=82,
)


_PROFILE = _descriptor.Descriptor(
  name='Profile',
  full_name='api.Profile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='age', full_name='api.Profile.age', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='api.Profile.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=120,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='api.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.Point.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=144,
)

_USER.fields_by_name['profile'].message_type = _PROFILE
_USER.fields_by_name['cache'].message_type = _POINT
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Profile'] = _PROFILE
DESCRIPTOR.message_types_by_name['Point'] = _POINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.User)
  ))
_sym_db.RegisterMessage(User)

Profile = _reflection.GeneratedProtocolMessageType('Profile', (_message.Message,), dict(
  DESCRIPTOR = _PROFILE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.Profile)
  ))
_sym_db.RegisterMessage(Profile)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.Point)
  ))
_sym_db.RegisterMessage(Point)



_USERGUIDE = _descriptor.ServiceDescriptor(
  name='UserGuide',
  full_name='api.UserGuide',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=146,
  serialized_end=237,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPoint',
    full_name='api.UserGuide.GetPoint',
    index=0,
    containing_service=None,
    input_type=_PROFILE,
    output_type=_POINT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListUsers',
    full_name='api.UserGuide.ListUsers',
    index=1,
    containing_service=None,
    input_type=_POINT,
    output_type=_USER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERGUIDE)

DESCRIPTOR.services_by_name['UserGuide'] = _USERGUIDE

# @@protoc_insertion_point(module_scope)
