// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Profile              *Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Cache                *Point   `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *User) GetCache() *Point {
	if m != nil {
		return m.Cache
	}
	return nil
}

type Profile struct {
	Age                  int32    `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Point struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*Profile)(nil), "api.Profile")
	proto.RegisterType((*Point)(nil), "api.Point")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x0a, 0xe0, 0x62, 0x09, 0x2d,
	0x4e, 0x2d, 0x12, 0x52, 0xe3, 0x62, 0x2f, 0x28, 0xca, 0x4f, 0xcb, 0xcc, 0x49, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x36, 0xe2, 0xd1, 0x03, 0xa9, 0x0c, 0x80, 0x88, 0x05, 0xc1, 0x24, 0x85, 0x14,
	0xb8, 0x58, 0x93, 0x13, 0x93, 0x33, 0x52, 0x25, 0x98, 0xc0, 0xaa, 0xb8, 0x20, 0xaa, 0xf2, 0x33,
	0xf3, 0x4a, 0x82, 0x20, 0x12, 0x4a, 0xfa, 0x5c, 0xec, 0x50, 0x5d, 0x42, 0x02, 0x5c, 0xcc, 0x89,
	0xe9, 0x10, 0x03, 0x59, 0x83, 0x40, 0x4c, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0x5c, 0x88, 0x6e,
	0xce, 0x20, 0x30, 0x5b, 0x49, 0x96, 0x8b, 0x15, 0x6c, 0x80, 0x90, 0x08, 0x17, 0x6b, 0x59, 0x62,
	0x4e, 0x29, 0x4c, 0x03, 0x84, 0x63, 0x14, 0xcd, 0xc5, 0x09, 0x72, 0xa1, 0x7b, 0x69, 0x66, 0x4a,
	0xaa, 0x90, 0x1a, 0x17, 0x87, 0x7b, 0x6a, 0x09, 0x44, 0x39, 0x8a, 0x0b, 0xa5, 0x90, 0x5c, 0xa2,
	0xc4, 0x20, 0xa4, 0xc6, 0xc5, 0xe9, 0x93, 0x59, 0x5c, 0x02, 0xd2, 0x58, 0x2c, 0x84, 0x24, 0x25,
	0xc5, 0x09, 0x66, 0x83, 0xc4, 0x95, 0x18, 0x0c, 0x18, 0x93, 0xd8, 0xc0, 0x41, 0x61, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x52, 0xc1, 0x04, 0xab, 0x17, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserGuideClient is the client API for UserGuide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserGuideClient interface {
	GetPoint(ctx context.Context, in *Profile, opts ...grpc.CallOption) (*Point, error)
	ListUsers(ctx context.Context, in *Point, opts ...grpc.CallOption) (UserGuide_ListUsersClient, error)
}

type userGuideClient struct {
	cc *grpc.ClientConn
}

func NewUserGuideClient(cc *grpc.ClientConn) UserGuideClient {
	return &userGuideClient{cc}
}

func (c *userGuideClient) GetPoint(ctx context.Context, in *Profile, opts ...grpc.CallOption) (*Point, error) {
	out := new(Point)
	err := c.cc.Invoke(ctx, "/api.UserGuide/GetPoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGuideClient) ListUsers(ctx context.Context, in *Point, opts ...grpc.CallOption) (UserGuide_ListUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserGuide_serviceDesc.Streams[0], "/api.UserGuide/ListUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &userGuideListUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserGuide_ListUsersClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type userGuideListUsersClient struct {
	grpc.ClientStream
}

func (x *userGuideListUsersClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserGuideServer is the server API for UserGuide service.
type UserGuideServer interface {
	GetPoint(context.Context, *Profile) (*Point, error)
	ListUsers(*Point, UserGuide_ListUsersServer) error
}

func RegisterUserGuideServer(s *grpc.Server, srv UserGuideServer) {
	s.RegisterService(&_UserGuide_serviceDesc, srv)
}

func _UserGuide_GetPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Profile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGuideServer).GetPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserGuide/GetPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGuideServer).GetPoint(ctx, req.(*Profile))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGuide_ListUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Point)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserGuideServer).ListUsers(m, &userGuideListUsersServer{stream})
}

type UserGuide_ListUsersServer interface {
	Send(*User) error
	grpc.ServerStream
}

type userGuideListUsersServer struct {
	grpc.ServerStream
}

func (x *userGuideListUsersServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

var _UserGuide_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.UserGuide",
	HandlerType: (*UserGuideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPoint",
			Handler:    _UserGuide_GetPoint_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListUsers",
			Handler:       _UserGuide_ListUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
